version: '3.7'

services:
  django:
    restart: always
    build: ./django
    expose:
      - "3031"
    depends_on:
      - db
    command: bash -c "python manage.py collectstatic --noinput &&
                      python manage.py migrate &&
                      cron &&
                      gunicorn data_collector.wsgi -b 0.0.0.0:3031"
    volumes:
      - staticdata:/code/staticfiles/
      - ./django:/code
      - /tmp/weblet_backup:/backup
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/static/"
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports: 
        - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
volumes:
  dbdata:
  staticdata:
