version: '3.7'

services:
  django:
    restart: always
    build: ./django
    depends_on:
      - db
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./django:/code
      - /dev/null:/code/data_collector/local_settings.py
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
