# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-25 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='ユーザID')),
                ('timestamp', models.IntegerField(default=0, verbose_name='タイムスタンプ')),
                ('state_data', models.CharField(default='', max_length=10000, verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(verbose_name='生年月日')),
                ('gendar', models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別')),
                ('blood', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB'), ('Other', 'その他')], max_length=10, verbose_name='血液型')),
                ('sleep_time_top', models.TimeField(default=datetime.time(0, 0), verbose_name='最高睡眠時間')),
                ('sleep_time_bottom', models.TimeField(default=datetime.time(0, 0), verbose_name='最低睡眠時間')),
                ('sport', models.CharField(choices=[('サッカー', 'サッカー'), ('野球', '野球'), ('ゴルフ', 'ゴルフ'), ('テニス', 'テニス'), ('バスケットボール', 'バスケットボール'), ('陸上競技', '陸上競技'), ('バドミントン', 'バドミントン'), ('卓球', '卓球'), ('バレーボール', 'バレーボール'), ('その他', 'その他')], max_length=10, verbose_name='好きなスポーツ')),
                ('music', models.CharField(choices=[('ロック', 'ロック'), ('歌謡曲', '歌謡曲'), ('クラシック', 'クラシック'), ('ジャズやブルース', 'ジャズやブルース'), ('フォーク', 'フォーク'), ('演歌・民謡', '演歌・民謡'), ('R&Bやソウル', 'R&Bやソウル'), ('ポップス', 'ポップス'), ('その他', 'その他')], max_length=10, verbose_name='好きな音楽のジャンル')),
                ('taste', models.CharField(choices=[('甘党', '甘党'), ('辛党', '辛党'), ('濃い味', '濃い味'), ('薄味', '薄味')], max_length=5, verbose_name='味覚のこだわり')),
                ('eat', models.IntegerField(default=50, verbose_name='1.口から食事ができる')),
                ('move', models.IntegerField(default=50, verbose_name='2.自分で動くことができる')),
                ('think', models.IntegerField(default=50, verbose_name='3.自分で考えることができる')),
                ('breath', models.IntegerField(default=50, verbose_name='4.自分で呼吸ができる')),
                ('fun', models.IntegerField(default=50, verbose_name='5.楽しみがある')),
                ('no_pain', models.IntegerField(default=50, verbose_name='6.苦痛がない')),
                ('rank1', models.IntegerField(default=0, verbose_name='生命の質 1位')),
                ('rank2', models.IntegerField(default=0, verbose_name='生命の質 2位')),
                ('rank3', models.IntegerField(default=0, verbose_name='生命の質 3位')),
                ('rank4', models.IntegerField(default=0, verbose_name='生命の質 4位')),
                ('rank5', models.IntegerField(default=0, verbose_name='生命の質 5位')),
                ('rank6', models.IntegerField(default=0, verbose_name='生命の質 6位')),
                ('tipi_j_01', models.IntegerField(default=4, verbose_name='01.活発で外交的だと思う')),
                ('tipi_j_02', models.IntegerField(default=4, verbose_name='02.他人に不満をもち，もめごとを起こしやすいと思う')),
                ('tipi_j_03', models.IntegerField(default=4, verbose_name='03.しっかりしていて，自分に厳しいと思う')),
                ('tipi_j_04', models.IntegerField(default=4, verbose_name='04.心配性で，うろたえやすいと思う')),
                ('tipi_j_05', models.IntegerField(default=4, verbose_name='05.新しいことが好きで，変わった考えをもつと思う')),
                ('tipi_j_06', models.IntegerField(default=4, verbose_name='06.ひかえめで，おとなしいと思う')),
                ('tipi_j_07', models.IntegerField(default=4, verbose_name='07.人に気をつかう，やさしい人間だと思う')),
                ('tipi_j_08', models.IntegerField(default=4, verbose_name='08.だらしなく，うっかりしていると思う')),
                ('tipi_j_09', models.IntegerField(default=4, verbose_name='09.冷静で，気分が安定していると思う')),
                ('tipi_j_10', models.IntegerField(default=4, verbose_name='10.発想力に欠けた，平凡な人間だと思う')),
                ('das_01', models.IntegerField(default=4, verbose_name='01.死後の世界はあると思う')),
                ('das_02', models.IntegerField(default=4, verbose_name='02.世の中には「霊」や「たたり」があると思う')),
                ('das_03', models.IntegerField(default=4, verbose_name='03.死んでも魂は残ると思う')),
                ('das_04', models.IntegerField(default=4, verbose_name='04.人は死後、また生まれ変わると思う')),
                ('das_05', models.IntegerField(default=4, verbose_name='05.死ぬことがこわい')),
                ('das_06', models.IntegerField(default=4, verbose_name='06.自分が死ぬことを考えると、不安になる')),
                ('das_07', models.IntegerField(default=4, verbose_name='07.死は恐ろしいものだと思う')),
                ('das_08', models.IntegerField(default=4, verbose_name='08.私は死を非常に恐れている')),
                ('das_09', models.IntegerField(default=4, verbose_name='09.私は、死とはこの世の苦しみから解放されることだと思っている')),
                ('das_10', models.IntegerField(default=4, verbose_name='10.私は死をこの人生の重荷からの解放と思っている')),
                ('das_11', models.IntegerField(default=4, verbose_name='11.死は痛みと苦しみからの解放である')),
                ('das_12', models.IntegerField(default=4, verbose_name='12.死は魂の解放をもたらしてくれる')),
                ('das_13', models.IntegerField(default=4, verbose_name='13.私は死について考えることを避けている')),
                ('das_14', models.IntegerField(default=4, verbose_name='14.どんなことをしても死を考えることを避けたい')),
                ('das_15', models.IntegerField(default=4, verbose_name='15.私は、死についての考えが思い浮かんでくると、いつもそれをはねのけようとする')),
                ('das_16', models.IntegerField(default=4, verbose_name='16.死は恐ろしいのであまり考えないようにしている')),
                ('das_17', models.IntegerField(default=4, verbose_name='17.私は人生にはっきりとした使命と目的を見出している ')),
                ('das_18', models.IntegerField(default=4, verbose_name='18.私は人生の意義、目的、使命を見出す能力が十分にある ')),
                ('das_19', models.IntegerField(default=4, verbose_name='19.私の人生について考えると、今ここにこうして生きている理由がはっきりとしている')),
                ('das_20', models.IntegerField(default=4, verbose_name='20.未来は明るい')),
                ('das_21', models.IntegerField(default=4, verbose_name='21.「死とは何だろう」とよく考える ')),
                ('das_22', models.IntegerField(default=4, verbose_name='22.自分の死について考えることがよくある ')),
                ('das_23', models.IntegerField(default=4, verbose_name='23.身近な人の死をよく考える')),
                ('das_24', models.IntegerField(default=4, verbose_name='24.家族や友人と死についてよく話す')),
                ('das_25', models.IntegerField(default=4, verbose_name='25.人の寿命はあらかじめ「決められている」と思う ')),
                ('das_26', models.IntegerField(default=4, verbose_name='26.寿命は最初から決まっていると思う')),
                ('das_27', models.IntegerField(default=4, verbose_name='27.人の生死は目に見えないカ(運命・神など)によって決められている')),
                ('yk', models.BooleanField(default=False, verbose_name='鎮痛薬・鎮静薬の使用')),
                ('tje', models.BooleanField(default=False, verbose_name='中心静脈栄養')),
                ('ke', models.BooleanField(default=False, verbose_name='胃ろうチューブからの栄養補給')),
                ('syo', models.BooleanField(default=False, verbose_name='末梢点滴')),
                ('zk', models.BooleanField(default=False, verbose_name='人工呼吸器')),
                ('ks', models.BooleanField(default=False, verbose_name='鼻チューブからの栄養補給')),
                ('zt', models.BooleanField(default=False, verbose_name='人工血液透析')),
                ('sm', models.BooleanField(default=False, verbose_name='心肺蘇生')),
                ('ot', models.BooleanField(default=False, verbose_name='その他の希望')),
            ],
        ),
    ]
