# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-03 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.BigIntegerField(default=0, verbose_name='タイムスタンプ'),
        ),
    ]
